---
sidebar: sidebar 
permalink: install-setup/cluster-setup.html 
keywords: afx, afx system, cluster setup, setup 
summary: 'Après l"installation de votre matériel AFX, vous pouvez finaliser la configuration du cluster ONTAP. Ce processus implique des phases de configuration associées que vous devez effectuer séquentiellement. Dans ce cadre, vous pouvez éventuellement ajouter les nœuds de calcul de données (DCN) exécutant l"AI Data Engine (AIDE), permettant ainsi au cluster de stockage AFX et au cluster DCN de fonctionner comme un seul système géré via le même plan de contrôle ONTAP.' 
---
= Configurez votre cluster ONTAP de système de stockage AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après l'installation de votre matériel AFX, vous pouvez finaliser la configuration du cluster ONTAP. Ce processus implique des phases de configuration associées que vous devez effectuer séquentiellement. Dans ce cadre, vous pouvez éventuellement ajouter les nœuds de calcul de données (DCN) exécutant l'AI Data Engine (AIDE), permettant ainsi au cluster de stockage AFX et au cluster DCN de fonctionner comme un seul système géré via le même plan de contrôle ONTAP.



== Préparez-vous à configurer un système de stockage AFX

Avant de configurer votre cluster ONTAP, vous devez consulter les exigences de base d'AFX et les considérations supplémentaires d'AIDE afin de vous assurer que vous disposez de toutes les informations et ressources nécessaires pour mener à bien le processus de configuration.



=== Exigences principales d'AFX

Plusieurs exigences fondamentales sont à prendre en compte lors de la configuration de votre cluster AFX.

.Installation matérielle
Assurez-vous d'avoir terminé l'installation matérielle de votre système AFX. Pour plus d'informations, voir link:../install-setup/install-setup-workflow.html["Installez votre système AFX"].

.Adressage IP de base
Vous avez besoin de la configuration d'adressage IP suivante :

* Adresse IP de gestion de cluster
+
L'adresse IP de gestion de cluster est une adresse IPv4 unique pour l'interface de gestion de cluster utilisée par l'administrateur de cluster pour accéder au SVM d'administration et gérer le cluster.  Vous pouvez obtenir cette adresse IP auprès de l’administrateur responsable de l’attribution des adresses IP dans votre organisation.

* Masque de sous-réseau du réseau
+
Lors de la configuration du cluster, ONTAP nécessite un ensemble d’interfaces réseau adaptées à votre configuration.  Vous pouvez ajuster la recommandation si nécessaire.



.Configuration réseau supplémentaire
Vous aurez également besoin des informations réseau suivantes :

* Adresse IP de la passerelle réseau
* noms de domaine DNS
* Adresses IP des serveurs de noms DNS
* Adresses IP du serveur NTP
* Masque de sous-réseau




=== Considérations supplémentaires relatives à l'AIDE

Lors de la première installation et configuration d'AFX, vous pouvez inclure en option NetApp AI Data Engine (AIDE). AIDE prend en charge deux modèles de déploiement : le logiciel AIDE sur des serveurs tiers ou des nœuds de calcul de données (DCN) fournis par NetApp. Si vous prévoyez de configurer AIDE, complétez d'abord les prérequis pour votre modèle de déploiement :

* Pour les déploiements de serveurs tiers, complétez https://docs.netapp.com/us-en/ai-data-engine/install-aide-server/aide-mde-server-hardware-requirements.html["Installation matérielle de AI Data Engine sur des serveurs tiers"^], puis https://docs.netapp.com/us-en/ai-data-engine/install-setup/install-aide-as-software.html["installer le logiciel AIDE sur des serveurs tiers"^].
* Pour les déploiements NetApp DCN, complétez https://docs.netapp.com/us-en/ai-data-engine/install-dcn/aide-dcn-hardware-requirements.html["Installation matérielle du AI Data Engine sur les nœuds de calcul de données fournis par NetApp"^].
* Obtenez les adresses et toute configuration réseau associée pour les nœuds de calcul.




== Effectuer la configuration initiale du cluster

Vous pouvez connecter votre ordinateur portable au cluster AFX et définir plusieurs valeurs de configuration globales.

.À propos de cette tâche
Il y a quatre zones du cluster AFX qui doivent être initialement configurées.  Les trois premiers sont obligatoires tandis que le dernier est facultatif.

.Étapes
. Découvrez votre réseau de clusters.
+
.. Connectez votre ordinateur portable au commutateur de gestion et accédez aux ordinateurs et périphériques du réseau.
.. Ouvrez l'explorateur de fichiers.
.. Sélectionnez *Réseau*, puis faites un clic droit et sélectionnez *Actualiser*.
.. Sélectionnez l’une des icônes ONTAP , puis acceptez tous les certificats affichés sur votre écran.
+
L'interface utilisateur du gestionnaire de système s'affiche.



. Définissez le mot de passe administrateur.
+
Fournir et vérifier le mot de passe pour le `admin` compte. Sélectionnez *Continuer*.

. Configurez les adresses IP pour le cluster AFX et les nœuds du contrôleur.
+
Fournissez les adresses IP et les masques de sous-réseau.

. Si vous installez AI Data Engine avec votre système de stockage AFX, veuillez fournir les adresses IP des trois nœuds de calcul.
. Configurez les services réseau, notamment DNS et NIS. Sélectionnez *Continue*.
+
Définissez les détails de vos serveurs DNS et NTP.

. Configurez éventuellement le cryptage.
+
Vous pouvez définir les détails du chiffrement du cluster. Sélectionnez *Continuer*.

+

NOTE: Pour plus d'informations sur la création d'un cluster pour un environnement non-Windows, consultez link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html["Créer un cluster ONTAP et joindre des nœuds"^].



.Quelle est la prochaine étape
Vous serez redirigé vers la page de connexion du gestionnaire système.  Effectuez les étapes décrites dans<<Configuration complète du cluster>> .



== Configuration complète du cluster

Une fois la configuration initiale effectuée, vous pouvez terminer la configuration du cluster ONTAP à l'aide de System Manager.

.À propos de cette tâche
Trois zones du cluster ONTAP du système AFX sont configurées lors de l'installation.  Complétez les trois si possible, mais seul le premier est obligatoire.

.Avant de commencer
Vous devez disposer des informations suivantes :

* Détails de configuration VLAN.
* Détails de configuration NAS et/ou S3.


.Étapes
. Sign in au Gestionnaire système à l’aide du compte administrateur que vous avez fourni lors de la configuration initiale du cluster.  Remarquez la fenêtre contextuelle en haut à droite avec trois options de configuration.
. Sélectionnez *VLAN et marquage* et sélectionnez les options réseau appropriées à votre environnement.
. Sélectionnez *Services réseau* et configurez les protocoles d'accès client pour le SVM de données par défaut.
. Sélectionnez *Conteneur de données* et créez un volume ou un bucket S3.


.Quelle est la prochaine étape
* Si vous avez inclus AIDE dans la configuration du cluster AFX, complétez les étapes de configuration supplémentaires d'AIDE. La configuration de l'authentification s'applique à tous les déploiements AIDE. Une licence est requise pour les déploiements NetApp DCN qui utilisent des fonctionnalités AIDE sous licence ; les déploiements de serveurs tiers sont axés sur les métadonnées et ne nécessitent pas de licence AIDE. Voir  https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html["Configurer AI Data Engine"^] pour plus d'informations.
* Tu devraislink:../get-started/prepare-cluster-admin.html["Préparez-vous à administrer AFX"] avant d'utiliser votre cluster AFX dans un environnement de production.




== Informations connexes

* link:../get-started/learn-about-aide.html["Découvrez le NetApp AI Data Engine"]
* link:../administer/configure-svm.html["Configurer un SVM AFX"]
* link:../get-started/prepare-cluster-admin.html["Préparez-vous à administrer AFX"]

