---
sidebar: sidebar 
permalink: secure-data/prepare-secure-data.html 
keywords: afx, afx system, prepare, prepare secure, prepare secure data 
summary: Avant de gérer vos données AFX, vous devez vous familiariser avec les principaux concepts et fonctionnalités. 
---
= Préparez-vous à sécuriser les données de votre système de stockage AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de gérer vos données AFX, vous devez vous familiariser avec les principaux concepts et fonctionnalités.


TIP: Étant donné que de nombreux concepts et procédures d’administration disponibles sur les systèmes AFF et FAS sont les mêmes que ceux des systèmes de stockage AFX, il peut être utile de consulter la documentation d’Unified ONTAP .



== Terminologie et options

Il existe plusieurs termes liés à la sécurité des données AFX que vous devez connaître.

Ransomware:: Un ransomware est un logiciel malveillant qui crypte les fichiers, les rendant inaccessibles à l'utilisateur.  Un certain type de paiement est généralement exigé pour décrypter les données.  NetApp ONTAP fournit des solutions de protection contre les ransomwares grâce à des fonctionnalités telles que la protection autonome contre les ransomwares (ARP).
Cryptage:: Le cryptage est le processus de conversion des données dans un format sécurisé qui ne peut pas être facilement lu sans autorisation appropriée.  ONTAP propose des technologies de cryptage logicielles et matérielles pour protéger les données au repos.  Cela garantit qu'il ne peut pas être lu si le support de stockage est réutilisé, retourné, égaré ou volé.  Ces solutions de chiffrement peuvent être gérées à l'aide d'un serveur de gestion de clés externe ou du gestionnaire de clés embarqué fourni par ONTAP.
Certificats numériques et PKI:: Un certificat numérique est un document électronique utilisé pour prouver la propriété d'une clé publique.  La clé publique et la clé privée associée peuvent être utilisées de diverses manières, notamment pour établir l'identité, généralement dans le cadre d'un cadre de sécurité plus large tel que TLS et IPsec.  Ces clés, ainsi que les protocoles de support et les normes de formatage, constituent la base de l’infrastructure à clés publiques (PKI).




== Informations connexes

* link:../administer/additional-ontap-svm.html["Administration supplémentaire d'AFX SVM"]
* link:../get-started/prepare-cluster-admin.html["Préparez-vous à administrer votre système AFX"]

