---
sidebar: sidebar 
permalink: secure-data/secure-ip-connections.html 
keywords: netapp afx, afx, ip security, ipsec, secure data, data security, encryption, data-in-flight, secure connections, hardware offload 
summary: 'IP Security (IPsec) est une norme de protocole Internet qui assure le chiffrement, l"intégrité et l"authentification des données pour le trafic circulant entre les points d"extrémité du réseau au niveau IP.  Vous pouvez utiliser IPsec pour renforcer la sécurité du réseau frontal entre un cluster AFX et les clients.' 
---
= Connexions IP sécurisées sur vos systèmes de stockage AFX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IP Security (IPsec) est une norme de protocole Internet qui assure le chiffrement, l'intégrité et l'authentification des données pour le trafic circulant entre les points d'extrémité du réseau au niveau IP.  Vous pouvez utiliser IPsec pour renforcer la sécurité du réseau frontal entre un cluster AFX et les clients.



== Configuration d'IPsec sur un système AFX

Les procédures de configuration IPsec pour les systèmes de stockage AFX sont les mêmes que pour les systèmes AFF et FAS , à l'exception des cartes de contrôleur d'interface réseau (NIC) prises en charge utilisées avec la fonction de déchargement matériel. Se référer à https://docs.netapp.com/us-en/ontap/networking/ipsec-prepare.html["Préparez-vous à configurer la sécurité IP pour le réseau ONTAP"^] pour plus d'informations.



== Fonction de déchargement matériel

Plusieurs opérations cryptographiques IPsec, telles que le chiffrement et les contrôles d'intégrité, peuvent être déportées vers une carte NIC compatible sur votre système AFX.  Cela peut améliorer considérablement les performances et le débit du trafic réseau protégé par IPsec.


NOTE: À partir d' ONTAP 9.18.1, la fonctionnalité de déchargement matériel IPsec est étendue pour prendre en charge le trafic IPv6.

Les cartes réseau suivantes sont prises en charge pour la fonction de déchargement matériel IPsec sur les systèmes de stockage AFX à partir d' ONTAP 9.17.1 :

* X50130B (contrôleur Ethernet 2 ports, 40G/100G)
* Contrôleur Ethernet X50131B (2 ports, 40G/100G/200G/400G)


Se référer à https://hwu.netapp.com/["Hardware Universe NetApp"^] pour plus d'informations sur les cartes prises en charge pour la version ONTAP exécutée sur votre système AFX.



== Informations connexes

* https://docs.netapp.com/us-en/ontap/networking/ipsec-prepare.html["Préparez-vous à configurer la sécurité IP pour le réseau ONTAP"^]
* https://hwu.netapp.com/["Hardware Universe NetApp"^]

