---
sidebar: sidebar 
permalink: faq-ontap-afx.html 
keywords: afx, afx system, faq, frequently asked questions 
summary: 'Cette liste FAQ fournit des réponses aux questions que les clients se posent généralement sur leur système de stockage AFX.  Il comprend des concepts et une terminologie qui peuvent être utiles pour explorer AFX plus en détail ou effectuer des tâches d"administration avancées.' 
---
= FAQ sur les systèmes de stockage AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cette liste FAQ fournit des réponses aux questions que vous pourriez avoir sur votre système de stockage AFX.  Il comprend des concepts et une terminologie qui peuvent être utiles pour explorer AFX plus en détail ou effectuer des tâches d'administration avancées.



== Général

.Qu'est-ce qu'une personnalité ONTAP ?
ONTAP est une plate-forme de stockage robuste et polyvalente, connue pour son ensemble complet de fonctionnalités et son adaptabilité à une large gamme d'exigences de stockage.  Bien que cette flexibilité en fasse un excellent choix pour les organisations ayant des charges de travail diverses, certains clients peuvent bénéficier d'une solution de stockage plus personnalisée et optimisée pour les besoins de leur environnement spécifique.

Pour répondre à ces besoins spécialisés, certains systèmes de stockage NetApp offrent des personnalités ONTAP distinctes, chacune incluant un ensemble de fonctionnalités conçues pour prendre en charge les exigences uniques du client.  Une personnalité ONTAP est généralement une combinaison de capacités matérielles et logicielles et spécialement conçue pour offrir une expérience optimisée pour les cas d'utilisation ciblés.  NetApp fournit trois personnalités ONTAP :

ONTAP unifié:: La personnalité Unified ONTAP offre un large ensemble de fonctionnalités de gestion des données, prenant en charge les protocoles NAS, SAN et S3 pour une flexibilité maximale.  Il s'agit de l'offre phare de NetApp , disponible sur les systèmes AFF et FAS ainsi que sur les déploiements virtualisés tels que ONTAP Select et Cloud Volumes ONTAP.
AFX:: La personnalité AFX ONTAP fournit une solution désagrégée conçue pour répondre aux exigences rigoureuses des charges de travail NAS et S3 hautes performances, y compris les applications AI/ML.  Les systèmes AFX offrent des fonctionnalités spécialisées aux clients nécessitant un stockage de fichiers et d'objets évolutif et à haut débit.
ASA r2:: La personnalité ASA r2 ONTAP fournit une solution désagrégée conçue spécifiquement pour les environnements SAN uniquement. https://docs.netapp.com/us-en/asa-r2/["Systèmes ASA r2"^]   rationalisez l'expérience de stockage pour les charges de travail en bloc, en offrant une gestion simplifiée et des performances optimisées pour les clients SAN.


En proposant ces personnalités ONTAP distinctes, NetApp permet aux organisations de sélectionner une solution de stockage adaptée à leurs exigences opérationnelles et à leurs charges de travail applicatives.

.Puis-je modifier la personnalité ONTAP de mon système de stockage NetApp ?
Non. La personnalité de votre système de stockage ONTAP est immuable et ne peut pas être modifiée.  Par exemple, vous ne pouvez pas convertir ou mettre à niveau un système de stockage FAS ou AFF (qui exécute la personnalité Unified ONTAP ) vers un système de stockage AFX.

.Les interfaces du gestionnaire système pour les différentes personnalités ONTAP se ressemblent toutes beaucoup.  Comment puis-je déterminer la personnalité d’un système spécifique ?
Dans le Gestionnaire système, sélectionnez *Cluster* dans le volet de navigation de gauche, puis *Vue d'ensemble*.  Vous verrez la personnalité affichée sur la page.  En guise d'alternative, vous pouvez exécuter la commande « system node show » sur la CLI.  Vous pouvez également déterminer la personnalité d'un cluster ONTAP à l'aide de l'API REST ; voirlink:./rest/first-call.html["Votre premier appel d'API REST du système AFX"] pour plus de détails.

.Que signifie « désagrégé » dans le contexte des systèmes de stockage AFX ?
Le terme « désagrégé » peut avoir deux significations différentes mais liées avec AFX selon le contexte.

Un concept important pour commencer est le découplage de la capacité de calcul des nœuds de contrôleur des étagères de stockage.  Avec AFX, les composants de calcul et de stockage du cluster ne sont plus étroitement couplés comme c'est le cas avec les systèmes FAS et AFF , qui exécutent la personnalité Unified ONTAP .  Au lieu de cela, ils sont connectés via des commutateurs de cluster.  Chaque contrôleur de nœud AFX dispose d'une vue complète de l'ensemble du pool de stockage du cluster.

Le deuxième concept lié au stockage désagrégé est que les agrégats et la gestion RAID sont supprimés en tant qu’entités administrables.  Une couche d'abstraction de stockage dans AFX configure et gère automatiquement les aspects de bas niveau du stockage, y compris les disques physiques et les groupes RAID.  Cela permet à l'administrateur AFX de se concentrer sur la configuration de stockage de haut niveau en fonction des volumes et des buckets.



== Interopérabilité

.Puis-je mélanger des nœuds système AFX avec des nœuds système AFF, ASA ou FAS dans le même cluster ONTAP ?
Non. Vous ne pouvez pas mélanger des nœuds système qui exécutent différentes personnalités ONTAP dans le même cluster. Par exemple, vous ne pouvez pas mélanger des nœuds AFX (qui exécutent la personnalité AFX ONTAP ) avec des nœuds AFF ou FAS (qui exécutent la personnalité Unified ONTAP ) dans le même cluster.

.Si je souhaite utiliser des systèmes exécutant Unified ONTAP (FAS, AFF, ASA) avec des systèmes AFX pour SnapMirror ou FlexCache, de quelle version ONTAP aurai-je besoin ?
Les règles de version de SnapMirror pour AFX sont identiques à celles d'Unified ONTAP.  Cela signifie que pour répliquer à partir d'Unified ONTAP, le système source doit se trouver dans la plage de versions prise en charge.  Pour répliquer à partir d'AFX, le système Unified ONTAP doit être à la ONTAP 9.16.1 ou ultérieure (la version la plus ancienne pour laquelle la fonctionnalité Advanced Capacity Balancing est prise en charge).  Pour FlexCache, les mêmes règles s'appliquent aux systèmes source et de destination comme décrit dans https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["TR-4743"^] .

Il existe quelques différences dans la prise en charge des volumes FlexGroup .  Un volume FlexGroup sur AFX ne peut pas être un volume d'origine pour un volume FlexCache utilisant le mode d'écriture différée.

.Puis-je effectuer des appels API ONTAPI (ZAPI) vers un cluster AFX ?
Non. Seule l'API REST ONTAP est prise en charge avec AFX.  Tout code d’automatisation qui utilise ZAPI doit être converti en API REST pour être utilisé avec AFX.



== Concepts avancés

.Quels sont les protocoles de données pris en charge avec un système de stockage AFX ?
Les protocoles de données pris en charge avec AFX incluent les suivants :

* NFSv3, NFSv4.0, NFSv4.1, NFSv4.2
* SMB2.x, SMB3.x
* S3
* NDMP


.Les protocoles de données fonctionnent-ils différemment dans AFX ?
Non. Les protocoles de données dans AFX fonctionnent de la même manière qu'avec les systèmes AFF et FAS .

.Le partitionnement de disque avancé (ADP) est-il utilisé dans AFX ?
Non. ADP n'est pas utilisé avec AFX.  Étant donné qu’il n’existe aucun agrégat racine avec AFX, la fonctionnalité ADP n’est pas nécessaire pour maximiser l’efficacité de l’espace disque.

.Puis-je utiliser n’importe quel type de commutateurs dans le réseau de cluster backend pour mon système AFX ?
Non. Seuls les commutateurs spécifiquement approuvés et fournis avec la plate-forme de stockage AFX sont pris en charge pour le réseau de cluster. De plus, ces commutateurs backend sont dédiés aux opérations de cluster AFX. Les opérations d’accès client (à l’aide de NFS, SMB et S3) doivent uniquement être effectuées sur le réseau de données client frontal.

.Comment les commutateurs du cluster sont-ils configurés ?
Les commutateurs réseau du cluster sont configurés à l’aide d’un fichier de configuration fourni par NetApp. Les modifications apportées au fichier de configuration ne sont pas prises en charge.

.Comment le stockage dans un cluster AFX est-il organisé ?
Tous les disques et étagères de stockage attachés à un cluster AFX font partie d'une zone de disponibilité de stockage (SAZ).  Chaque cluster AFX ne prend en charge qu'un seul SAZ qui ne peut pas être partagé entre les clusters AFX (à l'exception des opérations de réplication SnapMirror et FlexCache ).

Chaque nœud a une visibilité sur l’ensemble du stockage dans la SAZ.  Lorsque des étagères de stockage sont ajoutées à un cluster, ONTAP ajoute automatiquement les disques.

.En quoi les opérations de déplacement de volume fonctionnent-elles différemment avec AFX par rapport aux systèmes AFF ou FAS ?
Avec les systèmes AFF et FAS , qui exécutent la personnalité Unified ONTAP , il est possible de déplacer un volume sans interruption d'un nœud ou d'un agrégat vers un autre du cluster. Cette opération est réalisée à l'aide d'une opération de copie en arrière-plan avec la technologie SnapMirror , où un nouveau volume de destination est créé au nouvel emplacement. En fonction de la taille du volume et de l’utilisation des ressources du cluster, le temps nécessaire au déplacement d’un volume peut varier.

Avec AFX, il n’y a pas d’agrégats.  Tout le stockage est contenu dans une seule zone de disponibilité de stockage accessible par chaque nœud du cluster.  Par conséquent, les déplacements de volume n’ont jamais besoin de copier réellement les données.  Au lieu de cela, tous les déplacements de volume sont effectués avec des mises à jour de pointeur entre les nœuds.  Ceci est appelé déplacement de volume à copie zéro (ZCVM) et se produit instantanément car aucune donnée n'est réellement copiée ou déplacée.  Il s’agit essentiellement du même processus de déplacement de volume utilisé avec Unified ONTAP sans la copie SnapMirror .

Dans la version initiale d'AFX, les volumes ne se déplacent que dans les scénarios de basculement de stockage et lorsque des nœuds sont ajoutés ou supprimés du cluster. Ces mouvements sont contrôlés uniquement via ONTAP.

.Comment AFX détermine-t-il où placer les données dans la SAZ ?
AFX inclut une fonctionnalité appelée Gestion automatisée de la topologie (ATM) qui répond aux déséquilibres entre le système et les objets utilisateur.  L’objectif principal de l’ATM est d’équilibrer les volumes sur le cluster AFX.  Lorsqu'un déséquilibre est détecté, une tâche interne est déclenchée pour répartir uniformément les données sur les nœuds actifs.  Les données sont réaffectées à l'aide de ZCVM qui n'a besoin que de copier et de mettre à jour les métadonnées de l'objet.
