---
settings:
  name: AFX
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation AFX
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: administer
  - section: svm-admin
  - title: Maintenance du matériel
    url: "/maintain-hardware.html"
  - section: rest
  - section: learn-more
  - title: FAQ
    url: "/faq-ontap-afx.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
