---
sidebar: sidebar 
permalink: administer/additional-ontap-svm.html 
keywords: afx, afx system, additional administration, advanced administration 
summary: 'Outre l"administration AFX SVM classique, il peut y avoir d"autres tâches que vous devez effectuer en fonction de votre environnement.  La plupart des tâches supplémentaires peuvent être effectuées à l’aide du Gestionnaire système, même si dans certains cas, vous devrez peut-être utiliser l’interface de ligne de commande.' 
---
= Administration supplémentaire pour un système de stockage AFX SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Outre l'administration AFX SVM classique, il peut y avoir d'autres tâches que vous devez effectuer en fonction de votre environnement.  La plupart des tâches supplémentaires peuvent être effectuées à l’aide du Gestionnaire système, même si dans certains cas, vous devrez peut-être utiliser l’interface de ligne de commande.


NOTE: Les fonctionnalités et l'administration ONTAP décrites sont communes aux systèmes de stockage AFX et aux systèmes AFF ou FAS exécutant Unified ONTAP.  Des liens vers la documentation Unified ONTAP pertinente sont inclus, le cas échéant.



[[storage-management-and-performance]]
== Gestion du stockage et performances

Il existe plusieurs fonctionnalités facultatives de gestion du stockage et de performances que vous pouvez configurer et utiliser avec votre déploiement AFX.



[[ontap-nas-storage-management]]
=== Gestion du stockage NAS ONTAP

Le stockage en réseau (NAS) offre un stockage de fichiers dédié accessible par plusieurs clients du réseau. ONTAP prend en charge plusieurs protocoles NAS. En savoir plus https://docs.netapp.com/us-en/ontap/nas-management/index.html["Gestion du stockage NAS"^].



[[ontap-flexcache-volumes]]
=== Volumes ONTAP FlexCache

FlexCache est une fonctionnalité de mise en cache à distance d'ONTAP. Elle rapproche les données des clients, ce qui améliore les performances d'accès et réduit les coûts. La création d'un volume FlexCache, qui copie initialement uniquement les métadonnées du système de fichiers d'origine, simplifie la distribution des fichiers et réduit le trafic WAN. En savoir plus https://docs.netapp.com/us-en/ontap/flexcache/index.html["Volumes ONTAP FlexCache"^].



[[ontap-flexgroup-volumes]]
=== Volumes ONTAP FlexGroup

Un FlexGroup volume est composé de plusieurs volumes membres qui partagent le trafic automatiquement et de manière transparente. FlexGroup volumes offrent de nombreux avantages, notamment des performances élevées et une gestion simplifiée. En savoir plus https://docs.netapp.com/us-en/ontap/flexgroup/creation-workflow-task.html["Configuration du volume FlexGroup"^].



[[cross-file-sequential-read]]
=== Lecture séquentielle croisée de fichiers

La lecture séquentielle inter-fichiers (CFSR) est une fonctionnalité disponible sur les systèmes AFX à partir d'ONTAP 9.19.1 qui améliore les performances du montage vidéo et des applications associées. Pour les flux de travail stockant les images vidéo sous forme de fichiers séquentiels individuels, généralement de 50 à 250 Mo chacun, CFSR prédit et précharge intelligemment les fichiers suivants en fonction de la séquence des noms de fichiers. Jusqu'à 10 fichiers ou 500 Mo de données peuvent être préchargés, réduisant considérablement la latence de lecture et garantissant une lecture fluide des vidéos brutes 4K/8K à 30 images par seconde.

CFSR est activé par défaut sur les systèmes AFX exécutant ONTAP 9.19.1 ou une version ultérieure, mais vous devez l'activer explicitement sur les volumes individuels. Les administrateurs de stockage peuvent configurer cette fonctionnalité avec l'interface de ligne de commande ONTAP ou un appel d'API REST équivalent. En utilisant l'interface de ligne de commande, vous pouvez activer CFSR lors de la création d'un nouveau volume. Vous pouvez également mettre à jour un volume existant avec la commande suivante :

`volume modify -volume <volume_name> -aggressive-readahead-mode [cross_file_sequential_read|none]`

.Exemple
[source, bash]
----
volume modify -volume myvolume -aggressive-readahead-mode cross_file_sequential_read
volume show -volume myvolume -fields aggressive-readahead-mode
----
La fonctionnalité CFSR est compatible avec les volumes FlexVol et FlexGroup et est indépendante de l’extension de fichier, prenant en charge les schémas de numérotation de noms de fichiers décimaux et hexadécimaux. Pour les protocoles NFSv4.x, CFSR s’intègre aux capacités de lecture Multi-Protocol I/O (MPIO) pour améliorer davantage les performances en servant les lectures suivantes directement depuis la mémoire. CFSR est disponible exclusivement sur les systèmes AFX, avec des limitations concernant les volumes pris en charge. Il n’est pas pris en charge avec les types de volumes suivants :

* FabricPool-volumes activés
* Volumes de point de terminaison FlexCache
* Volumes de destination SnapMirror


CFSR n'est pas pris en charge sur les autres plateformes ONTAP (FAS, AFF ou ASA) ni dans les déploiements cloud, tels que Cloud Volumes ONTAP. Il peut fonctionner avec des volumes FlexGroup dont GDD est activé ou désactivé. Cependant, comme les fichiers d'images vidéo sont généralement beaucoup plus petits que la taille minimale de segment de GDD, ce dernier ne répartit pas efficacement ces fichiers entre les constituants FlexGroup. Cela signifie que l'impact direct de GDD sur le comportement de préchargement des fichiers de CFSR est minime.



[[data-protection]]
== Protection des données

Il existe plusieurs fonctionnalités de protection des données facultatives que vous pouvez configurer et utiliser avec votre déploiement AFX.



[[consistency-groups]]
=== Groupes de cohérence

Un groupe de cohérence est un ensemble de volumes gérés comme une seule unité. En savoir plus sur https://docs.netapp.com/us-en/ontap/consistency-groups/index.html["Groupes de cohérence ONTAP"^].



[[snaplock]]
=== SnapLock

Vous pouvez protéger vos fichiers en les convertissant en un état WORM (écriture une fois, lecture plusieurs fois) au niveau d'un volume. SnapLock prend en charge deux modes. Le mode Conformité garantit que les fichiers ne peuvent pas être supprimés avant l'expiration de leur période de conservation, ce qui répond aux exigences gouvernementales ou sectorielles. Le mode Entreprise permet aux utilisateurs privilégiés de supprimer des fichiers avant l'expiration de leur période de conservation. En savoir plus https://docs.netapp.com/us-en/ontap/snaplock/index.html["ONTAP SnapLock"^].



[[storage-efficiency]]
== efficacité de stockage

ONTAP propose plusieurs fonctionnalités d'efficacité du stockage qui peuvent vous aider à optimiser votre utilisation du stockage et à réduire vos coûts.



[[global-deduplication]]
=== Déduplication globale

https://docs.netapp.com/us-en/ontap/concepts/deduplication-concept.html["Déduplication"^] est une https://docs.netapp.com/us-en/ontap/volumes/deduplication-data-compression-efficiency-concept.html["Efficacité de stockage ONTAP"^] fonctionnalité qui permet de réduire les besoins en stockage physique en identifiant et en supprimant les blocs de données dupliqués. La déduplication traditionnelle s’effectue au niveau du volume ou de l’agrégat. Cette fonctionnalité existante offre une efficacité de stockage significative aux clients sur toutes les plateformes ONTAP.

À partir d'ONTAP 9.19.1, AFX introduit un nouveau périmètre opérationnel en étendant la déduplication à l'ensemble de la Storage Availability Zone (SAZ). La déduplication globale s'appuie sur la déduplication au niveau du volume en éliminant automatiquement les blocs dupliqués sur l'ensemble des volumes de la SAZ. Les sessions de déduplication globale sont déclenchées automatiquement, ce qui garantit des économies optimales sans intervention manuelle.

La déduplication globale est activée par défaut sur les systèmes AFX A1K et fonctionne de manière transparente en arrière-plan, avec un impact minimal sur les performances. Aucune licence de fonctionnalité n'est requise et la fonctionnalité s'intègre parfaitement aux technologies d'efficacité du stockage existantes, y compris la compression et la compaction. Les économies réalisées grâce à la déduplication globale sont rapportées via les indicateurs d'efficacité du stockage. Cette fonctionnalité peut être particulièrement bénéfique pour les charges de travail applicatives où les données sont fréquemment partagées ou répliquées sur plusieurs volumes.



[[security]]
== Sécurité

Il existe plusieurs fonctionnalités de sécurité facultatives que vous pouvez configurer et utiliser avec votre déploiement AFX.



[[fpolicy]]
=== Politique

FPolicy est un framework de notification d'accès aux fichiers utilisé pour surveiller et gérer les événements d'accès aux fichiers sur les machines virtuelles de stockage (SVM). Vous pouvez utiliser FPolicy pour créer des politiques qui définissent les opérations sur les fichiers à surveiller et, éventuellement, à bloquer, selon des critères que vous définissez. FPolicy est couramment utilisé pour l'audit de sécurité, la conformité et la gouvernance des données. En savoir plus https://docs.netapp.com/us-en/ontap/nas-audit/two-parts-fpolicy-solution-concept.html["Solutions ONTAP FPolicy"^].



[[ontap-event-and-performance-monitoring]]
== Surveillance des événements et des performances ONTAP

Vous pouvez surveiller l'état et les performances d'un cluster. Cela inclut la configuration d'alertes pour les événements et la gestion des notifications d'alertes de santé du système. En savoir plus sur https://docs.netapp.com/us-en/ontap/event-performance-monitoring/index.html["Surveillance des événements, des performances et de la santé"^].



[[related-information]]
== Informations connexes

* link:../faq-ontap-afx.html["FAQ sur les systèmes de stockage AFX"]
* link:../administer/additional-ontap-cluster.html["Administration supplémentaire pour les clusters AFX"]

