---
sidebar: sidebar 
permalink: administer/configure-svm.html 
keywords: afx, afx system, configure svm 
summary: Après avoir créé un SVM de données, vous pouvez mettre à jour la configuration en fonction de vos exigences et des besoins de vos clients. 
---
= Configurer un système de stockage AFX SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir créé un SVM de données, vous pouvez mettre à jour la configuration en fonction de vos exigences et des besoins de vos clients.

.À propos de cette tâche
Il existe quatre chemins d'accès à la configuration SVM, comme indiqué dans les onglets de la page de destination pour un SVM de données spécifique.  Il s’agit notamment de :

* Aperçu
+
Cela fournit un aperçu rapide du tableau de bord des détails de configuration actuels liés aux interfaces et services réseau, aux protocoles, au stockage et à la protection.

* Paramètres
+
Vous pouvez accéder et mettre à jour l'intégralité de la configuration SVM organisée en plusieurs domaines, tels que les protocoles, les services, les politiques et la sécurité.

* Réplication
+
Cette page fournit une liste des relations de réplication actuelles définies pour le SVM.

* Système de fichiers
+
Vous pouvez suivre l'activité et les analyses du SVM



.Avant de commencer
Vous devez décider quel SVM vous souhaitez afficher et mettre à jour.

.Étapes
. Dans le Gestionnaire système, sélectionnez *Cluster* puis *VM de stockage*.
. Sélectionnez le SVM souhaité, puis l'onglet *Paramètres*.
. Passez en revue les options de configuration sur la page ; sélectionnez et mettez à jour les paramètres comme vous le souhaitez.

