---
sidebar: sidebar 
permalink: get-started/compare-unified-ontap.html 
keywords: afx, afx system, compare afx, compare unified ontap 
summary: 'Les systèmes NetApp AFX exécutent une personnalité personnalisée d" ONTAP qui diffère de la personnalité ONTAP (appelée Unified ONTAP) qui s"exécute sur le stockage AFF et FAS .  Vous devez savoir en quoi les systèmes AFX sont similaires et différents des systèmes FAS et AFF .  Cela offre une perspective précieuse et peut être utile lors du déploiement d"AFX dans votre environnement.' 
---
= Comparez le système de stockage AFX aux systèmes AFF et FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les systèmes NetApp AFX exécutent une personnalité personnalisée d' ONTAP qui diffère de la personnalité ONTAP (appelée Unified ONTAP) qui s'exécute sur le stockage AFF et FAS .  Vous devez savoir en quoi les systèmes AFX sont similaires et différents des systèmes FAS et AFF .  Cela offre une perspective précieuse et peut être utile lors du déploiement d'AFX dans votre environnement.


TIP: La documentation AFX inclut des liens vers diverses rubriques du site de documentation Unified ONTAP pour plus de détails sur les fonctionnalités qui se comportent de la même manière quelle que soit la personnalité ONTAP .  Le contenu supplémentaire offre plus de profondeur qui peut être utile lors de l'administration de votre système de stockage AFX.



== Différences de configuration

Il existe quelques domaines dans lesquels la configuration AFX diffère des systèmes AFF et FAS .

Équilibrage avancé des capacités:: La fonction avancée d'équilibrage de capacité, contrôlée à l'aide du `-gdd` Le paramètre CLI est activé par défaut pour tous les volumes FlexGroup .




== Fonctionnalités Unified ONTAP non prises en charge ou restreintes

NetApp AFX est optimisé pour les charges de travail NAS et objets hautes performances.  De ce fait, il existe des différences avec AFF et FAS ainsi qu'avec les autres systèmes de stockage Unified ONTAP .  Les fonctionnalités suivantes ne sont pas disponibles avec le NetApp AFX ; la liste est organisée par fonctionnalité principale ou domaine fonctionnel.  Vous devriez également consulter les mises à jour et les modifications apportées à AFX danslink:../release-notes/whats-new-9171.html["Quoi de neuf"] en fonction de votre publication.



=== Bloc et SAN

* Administration SAN et accès client
* LUN et espaces de noms NVMe
* Approvisionnement épais en volumes




=== Granulats et stockage physique

* MetroCluster
* Agrégats appartenant à un nœud physique
* Gestion RAID
* Chiffrement agrégé NetApp (NAE)
* Déduplication au niveau agrégé
* SyncMirror (mise en miroir agrégée)
* Hiérarchisation de FabricPool




=== Réplication des données (SnapMirror)


NOTE: La réplication de toutes les données est prise en charge dans les deux sens entre Unified ONTAP et AFX, avec les mêmes restrictions de version décrites dans https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html["Versions ONTAP compatibles pour les relations SnapMirror"^] (à quelques exceptions mineures près).

* Aucune réplication d'un volume provenant d'un système AFF ou FAS contenant un espace de noms LUN ou NVMe n'est possible.
* Les volumes FlexGroup ne peuvent être répliqués d'AFX vers Unified ONTAP version 9.16.1 ou ultérieure (en raison de la nécessité d'un équilibrage de capacité avancé).




=== Facilité de gestion

* API ONTAPI (ZAPI)
* API REST pour les fonctionnalités non prises en charge (telles que MetroCluster)
* Quelques limitations initiales des API REST pour les statistiques de performance
* Support d'AIQ Unified Manager
* Grafana Harvest version 25.08.1 et ultérieures
* NetApp Trident version 25.10 et ultérieures




== Modifications apportées à l'interface de ligne de commande

L'interface de ligne de commande ONTAP disponible avec AFX reflète généralement l'interface de ligne de commande disponible avec les systèmes AFF et FAS .  Mais il existe plusieurs différences, notamment :

* Nouvelles commandes AFX liées à :
+
** Affichage de la capacité de la zone de disponibilité de stockage
** Support de démarrage


* Aucune commande liée au SAN
* Les commandes de gestion globale ne sont plus nécessaires
* L'affichage agrégé présente désormais l'intégralité de la zone de disponibilité de stockage (SAZ).




== Informations connexes

* link:../get-started/system-design.html["Caractéristiques du système AFX"]
* link:../get-started/software-architecture.html["Détails de l'architecture AFX"]
* link:../faq-ontap-afx.html["FAQ sur les systèmes de stockage AFX"]
* link:../administer/additional-ontap-cluster.html["Administration supplémentaire du cluster AFX"]
* link:../administer/additional-ontap-svm.html["Administration supplémentaire d'AFX SVM"]

