---
sidebar: sidebar 
permalink: release-notes/whats-new-9171.html 
keywords: 'afx, release notes, what"s new, 9.17.1' 
summary: Découvrez les nouvelles fonctionnalités incluses avec ONTAP 9.17.1 qui sont disponibles avec votre système de stockage AFX. 
---
= Nouveautés d' ONTAP 9.17.1 pour les systèmes de stockage AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez les nouvelles fonctionnalités incluses avec ONTAP 9.17.1 qui sont disponibles avec votre système de stockage AFX.


NOTE: Plusieurs nouvelles fonctionnalités sont disponibles pour AFX avec ONTAP 9.17.1. Certaines de ces fonctionnalités sont spécifiques à AFX, tandis que beaucoup d'autres proviennent d'une base de produits commune partagée. En plus de consulter les fonctionnalités AFX décrites ci-dessous, vous devriez également vous référer à https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9171.html["Quoi de neuf dans ONTAP 9.17.1"^].



[[platforms]]
== Plateformes

[cols="2,4"]
|===
| Mise à jour | Description 


| Plateformes  a| 
Les composants du système de stockage NetApp AFX suivants sont disponibles avec la technologie de support associée.  Ensemble, cette plate-forme offre une solution matérielle et logicielle unifiée qui crée une expérience simplifiée spécifique aux besoins des clients NAS et S3 hautes performances.

* Contrôleurs AFX 1K
* Étagères NX224
* Commutateurs Cisco Nexus 9332D-GX2B et Nexus 9364D-GX2A


|===


[[storage-resource-management-enhancements]]
== Améliorations de la gestion des ressources de stockage

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../manage-data/monitor-debug-storage.html[Surveiller et dépanner un système de stockage AFX]
 a| 
Les volumes créés sur les SVM nouvellement créées sur les clusters ONTAP alloués aux protocoles NAS ont l’analyse du système de fichiers (FSA) activée par défaut. FSA est automatiquement activée dès la création d’un volume, offrant des capacités d’analyse immédiates sans configuration supplémentaire.

|===


[[related-information]]
== Informations connexes

* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Points forts de la version ONTAP 9"^]

