---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: Découvrez les nouvelles fonctionnalités incluses dans ONTAP 9.18.1 et disponibles avec votre système de stockage AFX. 
---
= Nouveautés d' ONTAP 9.18.1 pour les systèmes de stockage AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez les nouvelles fonctionnalités incluses dans ONTAP 9.18.1 et disponibles avec votre système de stockage AFX.



== Améliorations de la gestion des ressources de stockage

[cols="2,4"]
|===
| Mise à jour | Description 


| Placement de volume amélioré  a| 
NetApp AFX répartit automatiquement les volumes entre tous les nœuds d'un cluster.  Dans les versions précédentes ONTAP , l'algorithme de placement était basé sur le nombre de volumes dans le cluster.  Chaque nœud se voit attribuer le même nombre de volumes, quelle que soit son activité.  À partir d' ONTAP 9.18.1, l'algorithme a été amélioré pour prendre en compte les performances des nœuds lors du placement ou du déplacement de volumes.  Il en résulte un meilleur équilibrage des performances entre les nœuds du cluster AFX, ce qui réduit considérablement la probabilité qu'un nœud unique soit surchargé.

|===
.Informations connexes
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Points forts de la version ONTAP 9"^]

