---
sidebar: sidebar 
permalink: release-notes/whats-new-9181.html 
keywords: 'afx, release notes, what"s new, 9.18.1' 
summary: Découvrez les nouvelles fonctionnalités incluses dans ONTAP 9.18.1 et disponibles avec votre système de stockage AFX. 
---
= Nouveautés d' ONTAP 9.18.1 pour les systèmes de stockage AFX
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Découvrez les nouvelles fonctionnalités incluses dans ONTAP 9.18.1 et disponibles avec votre système de stockage AFX.


NOTE: Plusieurs nouvelles fonctionnalités sont disponibles pour AFX avec ONTAP 9.18.1. Certaines de ces fonctionnalités sont spécifiques à AFX, tandis que beaucoup d'autres proviennent d'une base de produits commune. En plus de consulter les fonctionnalités AFX décrites ci-dessous, vous devriez également vous référer à  https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9181.html["Nouveautés d' ONTAP 9.18.1"^].



[[security]]
== Sécurité

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../administer/additional-ontap-cluster.html[Administration supplémentaire : déchargement matériel IPsec]
 a| 
La prise en charge du déchargement matériel IPsec est étendue à IPv6.



 a| 
xref:../administer/additional-ontap-cluster.html[Administration supplémentaire : algorithmes PQC OpenSSL]
 a| 
ONTAP prend en charge les algorithmes cryptographiques postquantiques pour SSL. Ces algorithmes offrent une protection supplémentaire contre d'éventuelles attaques informatiques quantiques futures et sont disponibles lorsque le mode FIPS de SSL est désactivé.

|===


[[storage-resource-management-enhancements]]
== Améliorations de la gestion des ressources de stockage

[cols="2,4"]
|===
| Mise à jour | Description 


| Placement de volume amélioré  a| 
NetApp AFX répartit automatiquement les volumes entre tous les nœuds d'un cluster.  Dans les versions précédentes ONTAP , l'algorithme de placement était basé sur le nombre de volumes dans le cluster.  Chaque nœud se voit attribuer le même nombre de volumes, quelle que soit son activité.  À partir d' ONTAP 9.18.1, l'algorithme a été amélioré pour prendre en compte les performances des nœuds lors du placement ou du déplacement de volumes.  Il en résulte un meilleur équilibrage des performances entre les nœuds du cluster AFX, ce qui réduit considérablement la probabilité qu'un nœud unique soit surchargé.



 a| 
xref:../administer/configure-svm.html[Prise en charge des groupes de stratégies QoS imbriqués à deux niveaux sur les SVM et les volumes]
 a| 
Vous pouvez attribuer une politique QoS à une SVM et aux volumes sous cette SVM en même temps.

|===
.Informations connexes
* https://docs.netapp.com/us-en/ontap/release-notes/index.html["Points forts de la version ONTAP 9"^]

